::mods_registerMod("mod_lots_o_names", 1, "Lots O' Names");
::mods_queue("mod_lots_o_names", null, function() {
    local northernNames = [
        "Adalwolf",
        "Ademaro",
        "Adhelm",
        "Adrian",
        "Aethelstan",
        "Agi",
        "Alaric",
        "Alcide",
        "Amalrich",
        "Azzo",
        "Bada",
        "Beric",
        "Botwulf",
        "Bran",
        "Brandon",
        "Caio",
        "Dagobert",
        "Detlef",
        "Donar",
        "Donnel",
        "Ermenrich",
        "Filibert",
        "Gianni",
        "Gotfrid",
        "Grifo",
        "Gustavo",
        "Hagano",
        "Heiko",
        "Igor",
        "Jason",
        "Jurgen",
        "Nico",
        "Odilo",
        "Odo",
        "Orfeo",
        "Otmar",
        "Ottokar",
        "Raginbert",
        "Raginhard",
        "Raginmund",
        "Rocco",
        "Romeo",
        "Siegbert",
        "Taddeo",
        "Tassilo",
        "Ucco",
        "Ugo",
        "Uhtric",
        "Waramunt",
        "Warin",
        "Wulfric",
    ];

    local barbarianNames = [
        "Agnar",
        "Airmanareiks",
        "Aki",
        "Alareiks",
        "Aleifr",
        "Arnfinnr",
        "Bada",
        "Baggi",
        "Bjorn",
        "Brandr",
        "Dagr",
        "Danr",
        "Finnr",
        "Flaemingr",
        "Fridtjofr",
        "Frodi",
        "Gauti",
        "Geirmundr",
        "Geirr",
        "Gudini",
        "Gudleifr",
        "Guma",
        "Halfdan",
        "Holmgeirr",
        "Hrothereiks",
        "Ingolfr",
        "Josteinn",
        "Knutr",
        "Oddr",
        "Odoavar",
        "Olvir",
        "Runi",
        "Snorri",
        "Sumarlidi",
        "Suni",
        "Sverrir",
        "Thorgnyr",
        "Thorir",
        "Throndr",
        "Tryggvi",
        "Ulfr",
        "Vagn",
        "Vragi",
        "Yngvarr"
    ];

    local barbarianTitles = [
        "Ale-Lover",
        "the Troll",
        "Karlsefni",
        "Skullsplitter",
        "Trollburster",
        "Berserk-Killer",
        "Foul-Fart",
        "Skokull",
        "the Firebrand",
        "the Powerful",
        "the Mighty",
        "the Berserk",
        "the Fearsome",
        "Little-Bear",
        "Break-Spear",
        "Man-Breaker",
        "Boggvir",
        "the Stout",
        "the Stupid",
        "Gellir",
        "Gerpir",
        "the Loud",
        "Grettir",
        "Jarngreipr",
        "Jarnbrjotr",
        "Half-Troll",
        "Hjalmbrjotr",
        "Hrokkineista",
        "the Raven",
        "Hoggvandi",
        "Illugi",
        "the Champion",
        "Kleggi",
        "the Crow",
        "the Amorous",
        "Laxakarl",
        "Leather-Neck",
        "Ormstunga",
        "the Squinter",
        "Smjorkull",
        "enn Surtr",
        "enn Orvondr",
        "Strad-Bjarni"
    ];

    local knightNames = [
        "Sir Achille",
        "Sir Aelfsige",
        "Sir Aelfwynn",
        "Sir Aethelstan",
        "Sir Agapito",
        "Sir Alcide",
        "Sir Anicho",
        "Sir Anselmo",
        "Sir Arstan",
        "Sir Arthur",
        "Sir Bors",
        "Sir Botwulf",
        "Sir Caio",
        "Sir Camillo",
        "Sir Chlotar",
        "Sir Cynebald",
        "Sir Elmo",
        "Sir Ercole",
        "Sir Fedor",
        "Sir Filibert",
        "Sir Galahad",
        "Sir Gareth",
        "Sir Gawain",
        "Sir Gereon",
        "Sir Giacomo",
        "Sir Godric",
        "Sir Godwin",
        "Sir Hektor"
        "Sir Jason",
        "Sir Leander",
        "Sir Leonida",
        "Sir Lysander",
        "Sir Owain",
        "Sir Pepin",
        "Sir Radobod",
        "Sir Ricmod",
        "Sir Rocco",
        "Sir Uhtric",
        "Sir Uther",
        "Sir Wandregisilus",
        "Sir Waramund",
        "Sir Wulfric",
    ];

    local southernNames = [
        "Aabid",
        "Aamir",
        "Aariz",
        "Abadir",
        "Abdi",
        "Abdul",
        "Abul",
        "Alam",
        "Arham",
        "Arib",
        "Arshad",
        "Arslan",
        "Ashiq",
        "Ashraf",
        "Ayoob",
        "Azmat",
        "Bilal",
        "Burhaan",
        "Dalil",
        "Faiq",
        "Faizan",
        "Farid",
        "Firas",
        "Gasser",
        "Ghalib",
        "Hazim",
        "Ihab",
        "Iman",
        "Iskandar",
        "Jabbar",
        "Khattab",
        "Majd",
        "Majid",
        "Mirza",
        "Muammar",
        "Muhajir",
        "Mutahar",
        "Naqib",
        "Sahil",
        "Sahr",
        "Tafim",
        "Tahar",
        "Uzaiz",
        "Wathiq",
        "Zafar",
        "Zuhni",
    ];

    local southernNamesLast = [
        "Al-Nur",
        "Al-Rauf",
        "Ibn Arham",
        "Ibn Faiq",
        "Ibn Farid",
        "Ibn Jabbar",
        "Ibn Khattab",
        "Ibn Khattab",
        "Ibn Majd",
        "Ibn Zafar",
        "Ibn Zuhni",
    ];

    local southernOfficerTitles = [
        "Al-Nur Ibn Faizan",
        "Al-Qahar Ibn Abihi",
        "Al-Rauf Ibn Uzaiz",
        "Al-Razzaq Ibn Amr",
        "Al-Wahid Ibn Faraz",
        "Ibn Abi Sufyan",
        "Ibn Arshad",
        "Ibn Arslan",
        "Ibn Beyazid",
        "Ibn Daamin",
    ];

    local gladiatorTitles = [
        "the Bronzed",
        "the Burnished",
        "the Conqueror",
        "the Jackal",
        "the Leopard",
        "the Pit Master",
        "the Scarred",
        "the Shining",
        "the Tempest",
        "the Undying",
        "the Unsullied",
    ];

    local sellswordTitles = [
        "the Demon",
        "the Depraved",
        "the Malicious",
        "Throat-Slitter",
        "the Rabid",
        "the Wicked",
        "the Crow",
        "the Raven",
        "the Sinister",
    ];

    local swordmasterTitles = [
        "the True",
        "the Trueblade",
        "Redblade",
        "the Flash",
        "the Honorable",
        "Brightblade",
        "the Lightning",
        "Liechtenauer",
        "Ringeck",
        "Talhoffer",
        "von Danzig",
        "Kal",
        "dei Liberi",
        "Meyer",
        "Mair",
        "von Speyer",
        "Falkner",
        "Folz",
        "Leckuchner",
        "Jud",
        "von der Nyssen",
        "Preuss",
        "Pauernfeindt",
        "von Siegmeister",
        "Mittermeyer",
        "von Schonkopf",
        "von Kreutzer",
        "the Laugher",
        "the Barber",
    ];

    local hedgeKnightTitles = [
        "the Ogre",
        "the Troll",
        "the Lancer",
        "the Morning Star",
        "the Steelforged",
        "the Little Bear",
        "von Salza",
        "von Rohrbach",
        "von Winterstein",
        "von Treyden",
        "von Habsburg",
        "von Bassenheim",
        "von Tunna",
        "von Malberg",
        "von Weissenstadt",
        "von Braunschweig",
        "von Grimmelstein",
        "Barthauser",
        "Bergengrun",
        "von Littenheim",
        "von Reuenthal",
        "von Stockhausen",
        "von Schneider",
        "Schurer",
        "Blackcloak",
        "the Strongboar",
        "the Blackguard",
        "the Redguard",
        "the Soulless",
        "the Eastern Brute",
        "the Western Brute",
        "the Northern Brute",
        "Strongarm",
        "the Hog",
    ];

    local orcWarlordNames = [
        "Thog",
        "Azog",
        "Ugluk Dagash",
        "Gothmog",
        "Bolg"
        "Magog Ulmgash"
        "Golfimbul",
        "Grishnakh",
        "Ornush Tagarr",
        "Mahur",
        "Lugdush",
        "Lurtz"
        "Nugushara",
        "Ghazhkull Thraka",
        "Hruk",
        "Gaz",
    ];

    local banditLeaderNames = [
        "%randomname% the Razor",
        "Grinning %randomname%",
        "%randomname% the Dwarf",
        "%randomname% the Sly",
        "%randomname% Blue-Cheek",
        "Two-Face",
        "%randomname% the Bear-Killer",
        "The Thirty-Man Slayer",
        "The Count",
        "%randomname% the Demon",
        "%randomname% the Flenser",
        "%randomname% the Sweetling",
    ];

    local gt = this.getroottable();
    gt.Const.Strings.CharacterNames.extend(northernNames);
    gt.Const.Strings.BarbarianNames.extend(barbarianNames);
    gt.Const.Strings.BarbarianTitles.extend(barbarianTitles);
    gt.Const.Strings.KnightNames.extend(knightNames);
    gt.Const.Strings.SouthernNames.extend(southernNames);
    gt.Const.Strings.SouthernNamesLast.extend(southernNamesLast);
    gt.Const.Strings.SouthernOfficerTitles.extend(southernOfficerTitles);
    gt.Const.Strings.GladiatorTitles.extend(gladiatorTitles);
    gt.Const.Strings.SellswordTitles.extend(sellswordTitles);
    gt.Const.Strings.SwordmasterTitles.extend(swordmasterTitles);
    gt.Const.Strings.HedgeKnightTitles.extend(hedgeKnightTitles);
    gt.Const.Strings.OrcWarlordNames.extend(orcWarlordNames);
    gt.Const.Strings.BanditLeaderNames.extend(banditLeaderNames);
});