local southernNames = [
    "Aabid",
    "Aamir",
    "Aariz",
    "Abadir",
    "Abdi",
    "Abdul",
    "Abul",
    "Alam",
    "Arham",
    "Arib",
    "Arshad",
    "Arslan",
    "Ashiq",
    "Ashraf",
    "Ayoob",
    "Azmat",
    "Bilal",
    "Burhaan",
    "Dalil",
    "Faiq",
    "Faizan",
    "Farid",
    "Firas",
    "Gasser",
    "Ghalib",
    "Hazim",
    "Ihab",
    "Iman",
    "Iskandar",
    "Jabbar",
    "Khattab",
    "Majd",
    "Majid",
    "Mirza",
    "Muammar",
    "Muhajir",
    "Mutahar",
    "Naqib",
    "Sahil",
    "Sahr",
    "Tafim",
    "Tahar",
    "Uzaiz",
    "Wathiq",
    "Zafar",
    "Zuhni",
];

local southernNamesLast = [
    "Al-Nur",
    "Al-Rauf",
    "Ibn Arham",
    "Ibn Faiq",
    "Ibn Farid",
    "Ibn Jabbar",
    "Ibn Khattab",
    "Ibn Khattab",
    "Ibn Majd",
    "Ibn Zafar",
    "Ibn Zuhni",
];

local southernOfficerTitles = [
    "Al-Nur Ibn Faizan",
    "Al-Qahar Ibn Abihi",
    "Al-Rauf Ibn Uzaiz",
    "Al-Razzaq Ibn Amr",
    "Al-Wahid Ibn Faraz",
    "Ibn Abi Sufyan",
    "Ibn Arshad",
    "Ibn Arslan",
    "Ibn Beyazid",
    "Ibn Daamin",
];

local gladiatorTitles = [
    "the Bronzed",
    "the Burnished",
    "the Conqueror",
    "the Jackal",
    "the Leopard",
    "the Pit Master",
    "the Scarred",
    "the Shining",
    "the Tempest",
    "the Undying",
    "the Unsullied",
];

::Const.Strings.SouthernNames.extend(southernNames);
::Const.Strings.SouthernNamesLast.extend(southernNamesLast);
::Const.Strings.SouthernOfficerTitles.extend(southernOfficerTitles);
::Const.Strings.GladiatorTitles.extend(gladiatorTitles);