local barbarianNames = [
    "Agnar",
    "Airmanareiks",
    "Aki",
    "Alareiks",
    "Aleifr",
    "Arnfinnr",
    "Bada",
    "Baggi",
    "Bjorn",
    "Brandr",
    "Dagr",
    "Danr",
    "Finnr",
    "Flaemingr",
    "Fridtjofr",
    "Frodi",
    "Gauti",
    "Geirmundr",
    "Geirr",
    "Gudini",
    "Gudleifr",
    "Guma",
    "Halfdan",
    "Holmgeirr",
    "Hrothereiks",
    "Ingolfr",
    "Josteinn",
    "Knutr",
    "Oddr",
    "Odoavar",
    "Olvir",
    "Runi",
    "Snorri",
    "Sumarlidi",
    "Suni",
    "Sverrir",
    "Thorgnyr",
    "Thorir",
    "Throndr",
    "Tryggvi",
    "Ulfr",
    "Vagn",
    "Vragi",
    "Yngvarr"
];

local barbarianTitles = [
    "Ale-Lover",
    "the Troll",
    "Karlsefni",
    "Skullsplitter",
    "Trollburster",
    "Berserk-Killer",
    "Foul-Fart",
    "Skokull",
    "the Firebrand",
    "the Powerful",
    "the Mighty",
    "the Berserk",
    "the Fearsome",
    "Little-Bear",
    "Break-Spear",
    "Man-Breaker",
    "Boggvir",
    "the Stout",
    "the Stupid",
    "Gellir",
    "Gerpir",
    "the Loud",
    "Grettir",
    "Jarngreipr",
    "Jarnbrjotr",
    "Half-Troll",
    "Hjalmbrjotr",
    "Hrokkineista",
    "the Raven",
    "Hoggvandi",
    "Illugi",
    "the Champion",
    "Kleggi",
    "the Crow",
    "the Amorous",
    "Laxakarl",
    "Leather-Neck",
    "Ormstunga",
    "the Squinter",
    "Smjorkull",
    "enn Surtr",
    "enn Orvondr",
    "Strad-Bjarni"
];

::Const.Strings.BarbarianNames.extend(barbarianNames);
::Const.Strings.BarbarianTitles.extend(barbarianTitles);